import { NextResponse } from "next/server"

const MODIFIERS = [
  "",
  "-urgente",
  "-24-horas",
  "-economico",
  "-barato",
  "-a-domicilio",
  "-cerca-de-mi",
  "-de-guardia",
  "-nocturno",
  "-festivos",
  "-rapido",
  "-ahora",
  "-hoy",
]

const PROBLEMS: Record<string, string[]> = {
  electricista: [
    "apagon",
    "cortocircuito",
    "olor-quemado",
    "diferencial-salta",
    "enchufes-no-funcionan",
    "luces-parpadean",
    "cuadro-electrico",
    "instalacion-electrica",
  ],
  fontanero: [
    "fuga-agua",
    "tuberia-rota",
    "inundacion",
    "atasco-grave",
    "grifo-gotea",
    "cisterna-no-funciona",
    "calentador",
    "humedad",
  ],
  cerrajero: ["puerta-bloqueada", "cerradura-rota", "llave-dentro", "robo", "cambio-cerradura", "copia-llaves"],
  desatascos: [
    "wc-atascado",
    "fregadero-atascado",
    "arqueta-atascada",
    "mal-olor",
    "ducha-atascada",
    "bajante-atascado",
  ],
  calderas: [
    "sin-agua-caliente",
    "caldera-no-enciende",
    "fuga-gas",
    "ruido-caldera",
    "revision-caldera",
    "cambio-caldera",
  ],
}

const CITIES = [
  // Catalunya - Barcelona
  "barcelona",
  "hospitalet-llobregat",
  "badalona",
  "terrassa",
  "sabadell",
  "mataro",
  "santa-coloma-gramenet",
  "cornella-llobregat",
  "sant-boi-llobregat",
  "rubi",
  "manresa",
  "vilanova-geltru",
  "viladecans",
  "castelldefels",
  "el-prat-llobregat",
  "granollers",
  "cerdanyola-valles",
  "mollet-valles",
  "gava",
  "esplugues-llobregat",
  "sant-cugat-valles",
  "sant-feliu-llobregat",
  "vic",
  "igualada",
  "martorell",
  "sant-adria-besos",
  "premia-mar",
  "montcada-reixac",
  "barbera-valles",
  "ripollet",
  "sant-vicenc-horts",
  "sitges",
  "palamos",
  "sant-joan-despi",
  "el-masnou",
  "sant-pere-ribes",
  "sant-andreu-barca",
  "calella",
  "pineda-mar",
  "arenys-mar",
  "canet-mar",
  "montgat",
  "tiana",
  "alella",
  "badia-valles",
  "la-garriga",
  "cardedeu",
  "les-franqueses-valles",
  "caldes-montbui",
  "palau-solita-plegamans",
  "sentmenat",
  "santa-perpetua-mogoda",
  "polunya",
  "llinars-valles",
  "sant-celoni",
  "tordera",
  "malgrat-mar",
  "santa-susanna",
  "palafolls",
  "olesa-montserrat",
  "esparreguera",
  "abrera",
  "vilafranca-penedes",
  "sant-sadurni-anoia",
  "gelida",
  "la-granada",
  "subirats",
  "castellvi-rosanes",
  "corbera-llobregat",
  "cervelló",
  "la-palma-cervello",
  "vallirana",
  "torrelles-llobregat",
  "begues",
  "sant-climent-llobregat",
  "sant-just-desvern",
  // Catalunya - Girona
  "girona",
  "figueres",
  "blanes",
  "lloret-mar",
  "olot",
  "salt",
  "palafrugell",
  "sant-feliu-guixols",
  "roses",
  "banyoles",
  "la-bisbal-emporda",
  "torroella-montgri",
  "calonge",
  "platja-aro",
  "tossa-mar",
  "arbucies",
  "hostalric",
  "angles",
  "santa-coloma-farners",
  "bescanó",
  "cassà-selva",
  "llagostera",
  "vidreres",
  "macanet-selva",
  "riudellots-selva",
  "quart",
  "fornells-selva",
  "caldes-malavella",
  "sils",
  "riudarenes",
  "breda",
  "vilablareix",
  // Catalunya - Tarragona
  "tarragona",
  "reus",
  "tortosa",
  "amposta",
  "valls",
  "vendrell",
  "cambrils",
  "salou",
  "vila-seca",
  "constantí",
  "calafell",
  "torredembarra",
  "altafulla",
  "cunit",
  "la-pobla-montornes",
  "el-morell",
  "la-canonja",
  "deltebre",
  "sant-carles-rapita",
  "alcanar",
  "roquetes",
  "mora-ebre",
  "gandesa",
  "horta-sant-joan",
  "bot",
  "falset",
  // Catalunya - Lleida
  "lleida",
  "balaguer",
  "tarrega",
  "mollerussa",
  "la-seu-urgell",
  "cervera",
  "solsona",
  "tremp",
  "ponts",
  "bellpuig",
  "les-borges-blanques",
  "alpicat",
  "almacelles",
  "alcarras",
  "torres-segre",
  "artesa-segre",
  // Madrid
  "madrid",
  "mostoles",
  "alcala-henares",
  "fuenlabrada",
  "leganes",
  "getafe",
  "alcorcon",
  "torrejon-ardoz",
  "parla",
  "alcobendas",
  "las-rozas",
  "pozuelo-alarcon",
  "majadahonda",
  "coslada",
  "rivas-vaciamadrid",
  "valdemoro",
  "collado-villalba",
  "aranjuez",
  "arganda-rey",
  "pinto",
  "tres-cantos",
  "san-sebastian-reyes",
  "boadilla-monte",
  "villaviciosa-odon",
  "navalcarnero",
  "humanes-madrid",
  "ciempozuelos",
  "san-martin-valdeiglesias",
  "arroyomolinos",
  "moralzarzal",
  "torrelodones",
  "galapagar",
  "alpedrete",
  "guadarrama",
  "el-escorial",
  "villalba",
  "colmenar-viejo",
  "algete",
  "san-agustin-guadalix",
  "miraflores-sierra",
  "soto-real",
  "paracuellos-jarama",
  "san-fernando-henares",
  "mejorada-campo",
  "velilla-san-antonio",
  "loeches",
  "villanueva-pardillo",
  "brunete",
  // Andalucia - Malaga
  "malaga",
  "marbella",
  "fuengirola",
  "torremolinos",
  "benalmadena",
  "mijas",
  "estepona",
  "nerja",
  "velez-malaga",
  "rincon-victoria",
  "alhaurin-grande",
  "alhaurin-torre",
  "coin",
  "cartama",
  "pizarra",
  "alora",
  "antequera",
  "ronda",
  "campillos",
  "archidona",
  "mollina",
  "torrox",
  "algarrobo",
  "frigiliana",
  "competa",
  "canillas-albaida",
  "manilva",
  "casares",
  "benahavis",
  "ojen",
  "monda",
  "guaro",
  "tolox",
  "yunquera",
  "el-burgo",
  "ardales",
  "teba",
  // Andalucia - Sevilla
  "sevilla",
  "dos-hermanas",
  "alcala-guadaira",
  "utrera",
  "mairena-aljarafe",
  "ecija",
  "carmona",
  "moron-frontera",
  "san-juan-aznalfarache",
  "coria-rio",
  "la-rinconada",
  "tomares",
  "bormujos",
  "gines",
  "castilleja-cuesta",
  "espartinas",
  "olivares",
  "sanlucar-mayor",
  "lora-rio",
  "camas",
  "santiponce",
  "valencina-concepcion",
  "gelves",
  "palomares-rio",
  "almensilla",
  "bollullos-mitacion",
  "pilas",
  "hinojos",
  "villamanrique-condesa",
  "aznalcazar",
  // Andalucia - Granada
  "granada",
  "motril",
  "almunecar",
  "baza",
  "guadix",
  "loja",
  "huescar",
  "santa-fe",
  "armilla",
  "maracena",
  "albolote",
  "atarfe",
  "pinos-puente",
  "las-gabias",
  "ogijares",
  "la-zubia",
  "cenes-vega",
  "monachil",
  "huetor-vega",
  "cájar",
  "gojar",
  "churriana-vega",
  "cullar-vega",
  "purchil",
  "chauchina",
  "fuente-vaqueros",
  "valderrubio",
  // Andalucia - Cordoba
  "cordoba",
  "lucena",
  "puente-genil",
  "montilla",
  "priego-cordoba",
  "cabra",
  "baena",
  "palma-rio",
  "pozoblanco",
  "peñarroya-pueblonuevo",
  "villanueva-cordoba",
  "hinojosa-duque",
  "aguilar-frontera",
  "fernan-nuñez",
  "la-carlota",
  // Andalucia - Cadiz
  "cadiz",
  "jerez-frontera",
  "algeciras",
  "san-fernando",
  "chiclana-frontera",
  "puerto-santa-maria",
  "la-linea-concepcion",
  "puerto-real",
  "sanlucar-barrameda",
  "el-puerto",
  "rota",
  "conil-frontera",
  "barbate",
  "tarifa",
  "vejer-frontera",
  "medina-sidonia",
  "arcos-frontera",
  "ubrique",
  "olvera",
  "villamartin",
  "bornos",
  "espera",
  "algodonales",
  // Andalucia - Almeria
  "almeria",
  "el-ejido",
  "roquetas-mar",
  "nijar",
  "adra",
  "vera",
  "huercal-overa",
  "albox",
  "vicar",
  "aguadulce",
  "garrucha",
  "mojacar",
  "carboneras",
  "pulpi",
  "cuevas-almanzora",
  "antas",
  "los-gallardos",
  "turre",
  "bedar",
  // Andalucia - Huelva
  "huelva",
  "lepe",
  "almonte",
  "isla-cristina",
  "ayamonte",
  "moguer",
  "punta-umbria",
  "cartaya",
  "aljaraque",
  "gibraleon",
  "la-palma-condado",
  "bollullos-condado",
  "rociana-condado",
  "bonares",
  "lucena-puerto",
  "palos-frontera",
  // Andalucia - Jaen
  "jaen",
  "linares",
  "ubeda",
  "baeza",
  "andujar",
  "martos",
  "alcala-real",
  "la-carolina",
  "alcaudete",
  "jodar",
  "mancha-real",
  "villacarrillo",
  "torredonjimeno",
  "torredelcampo",
  "villanueva-arzobispo",
  "santisteban-puerto",
  // Valencia
  "valencia",
  "alicante",
  "elche",
  "castellon-plana",
  "torrevieja",
  "orihuela",
  "benidorm",
  "gandia",
  "paterna",
  "sagunto",
  "torrent",
  "alzira",
  "ontinyent",
  "denia",
  "javea",
  "altea",
  "calpe",
  "villena",
  "elda",
  "petrer",
  "alcoy",
  "ibi",
  "cocentaina",
  "muro-alcoy",
  "banyeres-mariola",
  "villajoyosa",
  "campello",
  "san-juan-alicante",
  "mutxamel",
  "san-vicente-raspeig",
  "novelda",
  "aspe",
  "monforte-cid",
  "crevillent",
  "santa-pola",
  "guardamar-segura",
  "rojales",
  "pilar-horadada",
  "los-montesinos",
  "san-miguel-salinas",
  "algorfa",
  "jacarilla",
  "redovan",
  "callosa-segura",
  "almoradi",
  "dolores",
  "catral",
  "san-isidro",
  "granja-rocamora",
  "daya-nueva",
  "daya-vieja",
  "formentera-segura",
  "benejuzar",
  "bigastro",
  "benferri",
  "cox",
  "rafal",
  "benijofar",
  "pueblo-nuevo-benitatxell",
  "teulada",
  "moraira",
  // Pais Vasco
  "bilbao",
  "vitoria-gasteiz",
  "san-sebastian",
  "barakaldo",
  "getxo",
  "irun",
  "portugalete",
  "santurtzi",
  "basauri",
  "leioa",
  "erandio",
  "galdakao",
  "durango",
  "bermeo",
  "mungia",
  "gernika-lumo",
  "amorebieta-etxano",
  "arrigorriaga",
  "sestao",
  "trapagaran",
  "ortuella",
  "zierbena",
  "abanto-zierbena",
  "muskiz",
  "sopela",
  "plentzia",
  "barrika",
  "gorliz",
  "urduliz",
  "berango",
  "algorta",
  "neguri",
  "las-arenas",
  "romo",
  "eibar",
  "zarautz",
  "hondarribia",
  "errenteria",
  "hernani",
  "lasarte-oria",
  "tolosa",
  "andoain",
  "beasain",
  "azpeitia",
  // Galicia
  "vigo",
  "coruna",
  "ourense",
  "lugo",
  "santiago-compostela",
  "pontevedra",
  "ferrol",
  "narron",
  "oleiros",
  "arteixo",
  "culleredo",
  "cambre",
  "carballo",
  "ribeira",
  "boiro",
  "noia",
  "muros",
  "cee",
  "corcubion",
  "fisterra",
  "muxia",
  "camariñas",
  "laxe",
  "malpica-bergantinos",
  "ponteceso",
  "cabana-bergantinos",
  "coristanco",
  "santa-comba",
  "nigran",
  "baiona",
  "gondomar",
  "mos",
  "porriño",
  "tui",
  "salvaterra-miño",
  "as-neves",
  "arbo",
  "a-cañiza",
  "ponteareas",
  "mondariz",
  "mondariz-balneario",
  "covelo",
  "fornelos-montes",
  "pazos-borben",
  "soutomaior",
  // Murcia
  "murcia",
  "cartagena",
  "lorca",
  "molina-segura",
  "alcantarilla",
  "torre-pacheco",
  "yecla",
  "cieza",
  "jumilla",
  "caravaca-cruz",
  "totana",
  "mazarron",
  "aguilas",
  "alhama-murcia",
  "las-torres-cotillas",
  "san-javier",
  "san-pedro-pinatar",
  "los-alcazares",
  "la-union",
  "archena",
  "ceutí",
  "lorqui",
  "alguazas",
  "campos-rio",
  // Aragon
  "zaragoza",
  "huesca",
  "teruel",
  "calatayud",
  "utebo",
  "cuarte-huerva",
  "ejea-caballeros",
  "tarazona",
  "monzon",
  "barbastro",
  "fraga",
  "jaca",
  "sabiñanigo",
  "binefar",
  "alcaniz",
  "andorra",
  "caspe",
  "la-almunia-doña-godina",
  // Baleares
  "palma-mallorca",
  "calvia",
  "manacor",
  "llucmajor",
  "marratxi",
  "inca",
  "santa-margalida",
  "alcudia",
  "pollença",
  "soller",
  "felanitx",
  "santanyi",
  "campos",
  "ses-salines",
  "colonia-sant-jordi",
  "porto-cristo",
  "cala-ratjada",
  "ibiza",
  "santa-eulalia-rio",
  "san-antonio-abad",
  "san-jose",
  "mahon",
  "ciutadella-menorca",
  "alaior",
  "es-castell",
  // Canarias
  "las-palmas-gran-canaria",
  "telde",
  "arucas",
  "santa-lucia-tirajana",
  "san-bartolome-tirajana",
  "maspalomas",
  "playa-ingles",
  "vecindario",
  "aguimes",
  "ingenio",
  "moya",
  "guia",
  "galdar",
  "agaete",
  "santa-cruz-tenerife",
  "san-cristobal-laguna",
  "arona",
  "adeje",
  "granadilla-abona",
  "los-cristianos",
  "playa-americas",
  "costa-adeje",
  "puerto-cruz",
  "los-realejos",
  "orotava",
  "icod-vinos",
  "guimar",
  "candelaria",
  "tacoronte",
  "la-matanza-acentejo",
  // Castilla y Leon
  "valladolid",
  "burgos",
  "leon",
  "salamanca",
  "palencia",
  "zamora",
  "segovia",
  "avila",
  "soria",
  "aranda-duero",
  "miranda-ebro",
  "medina-campo",
  "laguna-duero",
  "ponferrada",
  "san-andres-rabanedo",
  "villaquilambre",
  "benavente",
  // Castilla-La Mancha
  "toledo",
  "ciudad-real",
  "albacete",
  "guadalajara",
  "cuenca",
  "talavera-reina",
  "puertollano",
  "hellin",
  "almansa",
  "villarrobledo",
  "tomelloso",
  "alcazar-san-juan",
  "valdepeñas",
  "manzanares",
  "daimiel",
  "miguelturra",
  "socuellamos",
  // Asturias
  "gijon",
  "oviedo",
  "aviles",
  "langreo",
  "mieres",
  "siero",
  "castrillon",
  "san-martin-rey-aurelio",
  "llanes",
  "villaviciosa",
  "cangas-onis",
  "ribadesella",
  "luarca",
  "navia",
  "tapia-casariego",
  "cudillero",
  "pravia",
  // Cantabria
  "santander",
  "torrelavega",
  "camargo",
  "piélagos",
  "castro-urdiales",
  "el-astillero",
  "laredo",
  "santoña",
  "noja",
  "isla",
  "arnuero",
  "bareyo",
  "meruelo",
  "colindres",
  "ampuero",
  "limpias",
  "guriezo",
  "ramales-victoria",
  // Navarra
  "pamplona",
  "tudela",
  "barañain",
  "burlada",
  "estella-lizarra",
  "zizur-mayor",
  "tafalla",
  "villava",
  "ansoain",
  "berriozar",
  "noain-valle-elorz",
  "cizur-menor",
  "mutilva",
  "sarriguren",
  "mendillorri",
  "echavacoiz",
  "rochapea",
  // La Rioja
  "logroño",
  "calahorra",
  "arnedo",
  "haro",
  "alfaro",
  "nájera",
  "santo-domingo-calzada",
  "lardero",
  "villamediana-iregua",
  // Extremadura
  "badajoz",
  "caceres",
  "merida",
  "plasencia",
  "don-benito",
  "villanueva-serena",
  "almendralejo",
  "montijo",
  "zafra",
  "villafranca-barros",
  "olivenza",
  "jerez-caballeros",
  "navalmoral-mata",
  "trujillo",
  "coria",
  "moraleja",
  "talayuela",
]

const PROFESSION_SLUGS = ["electricista", "fontanero", "cerrajero", "desatascos", "calderas"]

export const dynamic = "force-dynamic"
export const revalidate = 86400

export async function GET(request: Request, { params }: { params: { slug: string[] } }) {
  const { slug } = params
  const baseUrl = "https://rapidfix.es"
  const date = new Date().toISOString().split("T")[0]

  // Join all slug segments and remove .xml extension
  const rawId = slug.join("/")
  const id = rawId.endsWith(".xml") ? rawId.slice(0, -4) : rawId

  const urls: string[] = []

  if (id.endsWith("-problemas")) {
    const profession = id.replace("-problemas", "")
    const problems = PROBLEMS[profession] || []
    for (const problem of problems) {
      for (const city of CITIES) {
        urls.push(`${baseUrl}/problema/${profession}/${problem}/${city}`)
      }
    }
  } else if (id.startsWith("precio-") || id.startsWith("presupuesto-")) {
    const prefix = id.startsWith("precio-") ? "precio-" : "presupuesto-"
    const profession = id.replace(prefix, "")
    for (const city of CITIES) {
      urls.push(`${baseUrl}/${prefix}${profession}/${city}`)
    }
  } else {
    let profession = ""
    let modifier = ""

    for (const p of PROFESSION_SLUGS) {
      if (id === p) {
        profession = p
        break
      }
      for (const mod of MODIFIERS) {
        if (mod && id === `${p}${mod}`) {
          profession = p
          modifier = mod
          break
        }
      }
      if (profession) break
    }

    if (profession) {
      for (const city of CITIES) {
        if (modifier) {
          urls.push(`${baseUrl}/${profession}${modifier}/${city}`)
        } else {
          urls.push(`${baseUrl}/${profession}/${city}`)
        }
      }
    }
  }

  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'

  for (const url of urls) {
    xml += `  <url>\n`
    xml += `    <loc>${url}</loc>\n`
    xml += `    <lastmod>${date}</lastmod>\n`
    xml += `    <changefreq>weekly</changefreq>\n`
    xml += `    <priority>0.8</priority>\n`
    xml += `  </url>\n`
  }

  xml += "</urlset>"

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=86400",
    },
  })
}
